service: aws-lambda-weather-forecast
frameworkVersion: '2'

provider:
  name: aws
  lambdaHashingVersion: 20201221
  ecr:
    images:
      weatherforecast:
        path: ./

functions:
  fnwheatherforecast:
    image:
      name: weatherforecast
    events:
      - httpApi: '*'
    environment:
      NODE_OPTIONS: --enable-source-maps
