service: aws-lambda-weather-forecast
frameworkVersion: '2'

custom:
  secretId: 'weatherForecastSecrets'
  tableName: 'metricsTable'
  wheatherApiKeyAttribute: 'apiKey'

provider:
  name: aws
  lambdaHashingVersion: 20201221
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - 'secretsmanager:GetSecretValue'
          Resource: 'arn:aws:secretsmanager:us-east-1:570815509498:secret:weatherForecastSecrets-Ue5JVc'
        - Effect: 'Allow'
          Action:
            - '*'
          Resource:
            - Fn::GetAtt:
              - MetricsDatabase
              - Arn
  ecr:
    images:
      weatherforecast:
        path: ./

functions:
  fnwheatherforecast:
    image:
      name: weatherforecast
    events:
      - httpApi: '*'
    environment:
      NODE_OPTIONS: --enable-source-maps
      AWS_REGION_NAME: ${aws:region}
      DB_TABLE_NAME: ${self:custom.tableName}
      SECRET_ID: ${self:custom.secretId}
      WEATHER_API_KEY_ATTRIBUTE_NAME: ${self:custom.wheatherApiKeyAttribute}

resources:
  Resources:
    MetricsDatabase:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        TableName: ${self:custom.tableName}
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
