name: test-and-deploy-to-aws-using-serverless

on:
  push:
    branches:
      - master

  workflow_dispatch:

jobs:
  lint-test_build-deploy:
    name: Test on node ${{ matrix.node }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: [14]
        os: [ubuntu-latest]

    steps:
      - name: Get the repo code
        uses: actions/checkout@v2

      - name: Commit version
        env:
          GITHUB_SHA: ${{ github.sha }}
        run: echo "Commit versio $env.GITHUB_SHA"

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: npm ci, run lint and test
        run: |
          npm ci
          npm run lint
          npm test

      - name: Typescript compilation
        run: npm run build

      - name: Use Docker
        uses: actions-hub/docker/cli@master
        env:
          SKIP_LOGIN: true

      - name: Install Serverless Framework
        run: npm install -g serverless

      - name: Serverless AWS authentication
        run: |
          sls config credentials \
          --provider aws \
          --key ${{ secrets.AWS_ACCESS_KEY_ID }} \
          --secret ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Deploy Lambda functions
        run: sls deploy
